name: blog_server
version: 0.0.1
description: RESTful API server for blog.
dependencies:
  bliss:
    git:
      url: 'https://github.com/stwupton/bliss.git'
      ref: 'bugfix/regex_improvement'
  postgresql: '^0.3.3'
